import './globals.css';

export const metadata = {
  title: 'Next.js App Router',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <div className="min-h-screen">{children}</div>
      </body>
    </html>
  );
}
