import './globals.css';

export const metadata = {
  title: 'Next.js App Router',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <p>This is header</p>
        </header>

        {children}

        <footer>
          <p>This is footer</p>
        </footer>
      </body>
    </html>
  );
}
